export enum ReportStatus {
  DRAFT = 'DRAFT',
  PENDING_INSPECTION = 'PENDING_INSPECTION',
  PENDING_SM_REVIEW = 'PENDING_SM_REVIEW',
  PENDING_GM_APPROVAL = 'PENDING_GM_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  COMPONENTS_ISSUED = 'COMPONENTS_ISSUED',
  REWORK_IN_PROGRESS = 'REWORK_IN_PROGRESS',
  NEW_PRODUCTION = 'NEW_PRODUCTION',
  CLOSED = 'CLOSED',
}

export enum RaisedByRole {
  OPERATOR = 'OPERATOR',
  INSPECTOR = 'INSPECTOR',
  SENIOR_MANAGER = 'SENIOR_MANAGER',
}

export enum Decision {
  REWORK = 'REWORK',
  SCRAP = 'SCRAP',
  ALTERNATIVE = 'ALTERNATIVE',
}

export enum ResponsibleParty {
  OPERATOR = 'OPERATOR',
  VENDOR = 'VENDOR',
  PROCESS = 'PROCESS',
  MACHINE = 'MACHINE',
}

export enum RecoveryStatus {
  PENDING = 'PENDING',
  RAISED = 'RAISED',
  RECOVERED = 'RECOVERED',
  PARTIALLY_RECOVERED = 'PARTIALLY_RECOVERED',
  WAIVED = 'WAIVED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  APP = 'APP',
}

export enum NotificationStatus {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  FAILED = 'FAILED',
  DELIVERED = 'DELIVERED',
}
