export enum Role {
  OPERATOR = 'OPERATOR',
  INSPECTOR = 'INSPECTOR',
  SENIOR_MANAGER = 'SENIOR_MANAGER',
  GENERAL_MANAGER = 'GENERAL_MANAGER',
  STORE_MANAGER = 'STORE_MANAGER',
  SALES = 'SALES',
  ADMIN = 'ADMIN',
}
