import * as XLSX from 'xlsx';

const COMPANY_NAME = 'Velan Metrology';
const REPORT_TITLE = 'Defect History Report';

function formatDate(date) {
  const d = date instanceof Date ? date : new Date(date);
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function formatDateTime(date) {
  const d = date instanceof Date ? date : new Date(date);
  return d.toLocaleString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', hour12: true
  });
}

function buildFilterSummary(filters) {
  const parts = [];
  if (filters.search) parts.push(`Search: "${filters.search}"`);
  if (filters.component) parts.push(`Component: ${filters.component}`);
  if (filters.vendor) parts.push(`Vendor: ${filters.vendor}`);
  if (filters.operator) parts.push(`Operator: ${filters.operator}`);
  if (filters.errorType) parts.push(`Error Type: ${filters.errorType}`);
  if (filters.stage) parts.push(`Stage: ${filters.stage}`);
  if (filters.status) parts.push(`Status: ${filters.status}`);
  if (filters.startDate) parts.push(`From: ${formatDate(filters.startDate)}`);
  if (filters.endDate) parts.push(`To: ${formatDate(filters.endDate)}`);
  return parts.length ? parts.join(', ') : 'None';
}

function flattenReports(reports) {
  return reports.map(r => ({
    'Report No': r.reportNumber || '—',
    'SC / PO Number': `${r.scNo || '—'} / ${r.poNo || '—'}`,
    'Component': r.componentName || '—',
    'Error Type': r.errorTypeName || r.inspectionDetail?.errorType || '—',
    'Responsible Party': r.inspectionDetail?.responsibleParty || '—',
    'Stage of Failure': r.rejectionFailedStage || r.inspectionDetail?.rejectionFailedStage || r.stageOfFailure || '—',
    'Status': r.status || '—',
    'Total Cost': r.inspectionDetail?.costEstimate || 0,
    'Date': r.createdAt ? formatDate(r.createdAt) : '—'
  }));
}

function computeSummary(reports) {
  const total = reports.length;
  const open = reports.filter(r => !['CLOSED', 'APPROVED', 'REJECTED'].includes(r?.status)).length;
  const closed = reports.filter(r => r?.status === 'CLOSED').length;
  const pending = reports.filter(r => ['PENDING_INSPECTION', 'PENDING_ACCOUNTS_REVIEW', 'PENDING_SM_REVIEW', 'PENDING_GM_APPROVAL'].includes(r?.status)).length;
  const vendorCases = reports.filter(r => r.inspectionDetail?.responsibleParty === 'VENDOR').length;
  const operatorCases = reports.filter(r => r.inspectionDetail?.responsibleParty === 'OPERATOR').length;
  const totalCost = reports.reduce((sum, r) => sum + (Number(r.inspectionDetail?.costEstimate) || 0), 0);
  const avgCost = total > 0 ? Math.round(totalCost / total) : 0;
  return { total, open, closed, pending, vendorCases, operatorCases, totalCost, avgCost };
}

export function exportToExcel(reports, filters, user) {
  const flat = flattenReports(reports);
  const summary = computeSummary(reports);
  const now = new Date();

  const wb = XLSX.utils.book_new();

  const headerRows = [
    [COMPANY_NAME],
    [REPORT_TITLE],
    [],
    ['Generated:', formatDateTime(now)],
    ['Generated By:', user?.name || user?.username || 'N/A'],
    ['Applied Filters:', buildFilterSummary(filters)],
    [],
    ['SUMMARY STATISTICS'],
    ['Total Records', summary.total],
    ['Open Reports', summary.open],
    ['Closed Reports', summary.closed],
    ['Pending Reports', summary.pending],
    ['Vendor Cases', summary.vendorCases],
    ['Operator Cases', summary.operatorCases],
    ['Total Cost', summary.totalCost],
    ['Average Cost', summary.avgCost],
    [],
  ];

  const headerOffset = headerRows.length;

  const columns = Object.keys(flat[0] || {});
  const dataRows = flat.map(r => columns.map(c => r[c]));

  const wsData = [
    ...headerRows.map(r => r),
    columns,
    ...dataRows,
  ];

  const ws = XLSX.utils.aoa_to_sheet(wsData);

  const colWidths = columns.map(c => {
    const maxLen = Math.max(
      c.length,
      ...flat.map(r => String(r[c] || '').length)
    );
    return { wch: Math.min(Math.max(maxLen + 3, 12), 40) };
  });
  ws['!cols'] = colWidths;

  const range = XLSX.utils.decode_range(ws['!ref']);
  const headerRowIdx = headerOffset;
  const dataStart = headerOffset + 1;

  for (let C = range.s.c; C <= range.e.c; C++) {
    const addr = XLSX.utils.encode_cell({ r: headerRowIdx, c: C });
    if (!ws[addr]) continue;
    ws[addr].s = {
      font: { bold: true, color: { rgb: 'FFFFFF' }, sz: 11, name: 'Calibri' },
      fill: { fgColor: { rgb: '1F4E79' } },
      alignment: { horizontal: 'center', vertical: 'center', wrapText: true },
      border: {
        top: { style: 'thin', color: { rgb: 'D0D0D0' } },
        bottom: { style: 'thin', color: { rgb: 'D0D0D0' } },
        left: { style: 'thin', color: { rgb: 'D0D0D0' } },
        right: { style: 'thin', color: { rgb: 'D0D0D0' } },
      },
    };
  }

  for (let R = dataStart; R <= range.e.r; R++) {
    const isEven = (R - dataStart) % 2 === 0;
    for (let C = range.s.c; C <= range.e.c; C++) {
      const addr = XLSX.utils.encode_cell({ r: R, c: C });
      if (!ws[addr]) ws[addr] = { t: 's', v: '' };
      const cell = ws[addr];

      const colKey = columns[C];
      const isCostCol = colKey === 'Total Cost';
      const isDateCol = colKey === 'Date';

      cell.s = {
        font: { sz: 10, name: 'Calibri', color: { rgb: isEven ? '333333' : '1a1a1a' } },
        fill: { fgColor: { rgb: isEven ? 'F2F7FB' : 'FFFFFF' } },
        alignment: {
          horizontal: isCostCol ? 'right' : 'left',
          vertical: 'center',
        },
        border: {
          top: { style: 'thin', color: { rgb: 'E0E0E0' } },
          bottom: { style: 'thin', color: { rgb: 'E0E0E0' } },
          left: { style: 'thin', color: { rgb: 'E0E0E0' } },
          right: { style: 'thin', color: { rgb: 'E0E0E0' } },
        },
      };

      if (isCostCol && typeof cell.v === 'number') {
        cell.t = 'n';
        cell.z = '$#,##0';
      }

      if (isDateCol) {
        cell.alignment = { horizontal: 'center', vertical: 'center' };
      }
    }
  }

  for (let R = 0; R < headerOffset; R++) {
    for (let C = range.s.c; C <= range.e.c; C++) {
      const addr = XLSX.utils.encode_cell({ r: R, c: C });
      if (!ws[addr]) continue;
      ws[addr].s = {
        font: { sz: R === 0 ? 16 : R === 1 ? 14 : 10, bold: R < 3, name: 'Calibri', color: { rgb: R < 3 ? '1F4E79' : '555555' } },
      };
    }
  }

  const summaryStart = 7;
  const summaryEnd = 15;
  for (let R = summaryStart; R <= summaryEnd; R++) {
    const cellA = ws[XLSX.utils.encode_cell({ r: R, c: 0 })];
    const cellB = ws[XLSX.utils.encode_cell({ r: R, c: 1 })];
    if (cellA) {
      cellA.s = {
        ...cellA.s,
        font: { ...cellA.s?.font, bold: R === summaryStart, sz: R === summaryStart ? 11 : 10 },
        fill: { fgColor: { rgb: R === summaryStart ? '1F4E79' : 'E8F0FE' } },
      };
      if (cellA.s.font) cellA.s.font.color = { rgb: R === summaryStart ? 'FFFFFF' : '333333' };
    }
    if (cellB) {
      cellB.s = {
        ...cellB.s,
        font: { sz: 10, bold: true, name: 'Calibri', color: { rgb: '1F4E79' } },
        alignment: { horizontal: 'right', vertical: 'center' },
      };
      if (R === 14 || R === 15) {
        cellB.z = '$#,##0';
      }
    }
  }

  ws['!freeze'] = { xRef: 0, yRef: headerOffset + 1 };

  XLSX.utils.book_append_sheet(wb, ws, 'Defect History');

  const fileName = `Defect_History_Report_${now.getFullYear()}_${String(now.getMonth() + 1).padStart(2, '0')}_${String(now.getDate()).padStart(2, '0')}_${String(now.getHours()).padStart(2, '0')}_${String(now.getMinutes()).padStart(2, '0')}.xlsx`;

  XLSX.writeFile(wb, fileName);
}
