import jsPDF from 'jspdf';
import 'jspdf-autotable';

const COMPANY_NAME = 'Velan Metrology';
const REPORT_TITLE = 'Enterprise Error Correction Report';
const PAGE_WIDTH = 297;
const PAGE_HEIGHT = 210;
const MARGIN = 12;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function formatDate(date) {
  const d = date instanceof Date ? date : new Date(date);
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function formatDateTime(date) {
  const d = date instanceof Date ? date : new Date(date);
  return d.toLocaleString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', hour12: true
  });
}

function buildFilterSummary(filters) {
  const parts = [];
  if (filters.search) parts.push(`Search: "${filters.search}"`);
  if (filters.component) parts.push(`Component: ${filters.component}`);
  if (filters.vendor) parts.push(`Vendor: ${filters.vendor}`);
  if (filters.operator) parts.push(`Operator: ${filters.operator}`);
  if (filters.errorType) parts.push(`Error Type: ${filters.errorType}`);
  if (filters.stage) parts.push(`Stage: ${filters.stage}`);
  if (filters.status) parts.push(`Status: ${filters.status}`);
  if (filters.startDate) parts.push(`From: ${formatDate(filters.startDate)}`);
  if (filters.endDate) parts.push(`To: ${formatDate(filters.endDate)}`);
  return parts.length ? parts.join(', ') : 'None';
}

function computeSummary(reports) {
  const total = reports.length;
  const open = reports.filter(r => !['CLOSED', 'APPROVED', 'REJECTED'].includes(r?.status)).length;
  const closed = reports.filter(r => r?.status === 'CLOSED').length;
  const pending = reports.filter(r => ['PENDING_INSPECTION', 'PENDING_ACCOUNTS_REVIEW', 'PENDING_SM_REVIEW', 'PENDING_GM_APPROVAL'].includes(r?.status)).length;
  const vendorCases = reports.filter(r => r.inspectionDetail?.responsibleParty === 'VENDOR').length;
  const operatorCases = reports.filter(r => r.inspectionDetail?.responsibleParty === 'OPERATOR').length;
  const totalCost = reports.reduce((sum, r) => sum + (Number(r.inspectionDetail?.costEstimate) || 0), 0);
  const avgCost = total > 0 ? Math.round(totalCost / total) : 0;
  return { total, open, closed, pending, vendorCases, operatorCases, totalCost, avgCost };
}

function addHeader(doc) {
  doc.setFontSize(16);
  doc.setTextColor(31, 78, 121);
  doc.setFont(undefined, 'bold');
  doc.text(COMPANY_NAME, PAGE_WIDTH / 2, MARGIN + 6, { align: 'center' });
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.setFont(undefined, 'normal');
  doc.text(REPORT_TITLE, PAGE_WIDTH / 2, MARGIN + 13, { align: 'center' });
  doc.setDrawColor(31, 78, 121);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, MARGIN + 16, PAGE_WIDTH - MARGIN, MARGIN + 16);
}

function addFooter(doc, pageNum, totalPages) {
  const str = `Page ${pageNum} of ${totalPages} | ${COMPANY_NAME} | Confidential`;
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text(str, PAGE_WIDTH / 2, PAGE_HEIGHT - 6, { align: 'center' });
}

function addWatermark(doc) {
  doc.saveGraphicsState();
  doc.setFontSize(60);
  doc.setTextColor(220, 220, 220);
  doc.setGState(doc.GState({ opacity: 0.15 }));
  doc.text('CONFIDENTIAL', PAGE_WIDTH / 2, PAGE_HEIGHT / 2, {
    align: 'center',
    angle: 45,
  });
  doc.restoreGraphicsState();
}

export function exportToPDF(reports, filters, user) {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const summary = computeSummary(reports);
  const now = new Date();

  const tableHeaders = [
    ['Report No', 'SC / PO Number', 'Component', 'Error Type', 'Responsible', 'Stage of Failure', 'Status', 'Total Cost', 'Date'],
  ];

  const tableData = reports.map(r => [
    r.reportNumber || '—',
    `${r.scNo || '—'} / ${r.poNo || '—'}`,
    r.componentName || '—',
    r.errorTypeName || r.inspectionDetail?.errorType || '—',
    r.inspectionDetail?.responsibleParty || '—',
    r.rejectionFailedStage || r.inspectionDetail?.rejectionFailedStage || r.stageOfFailure || '—',
    r.status || '—',
    { content: `$${Number(r.inspectionDetail?.costEstimate || 0).toLocaleString('en-US')}`, styles: { halign: 'right' } },
    r.createdAt ? formatDate(r.createdAt) : '—',
  ]);

  let pageNum = 1;
  let totalPages = 1;

  doc.addPage = (function (origFn) {
    return function () {
      origFn.call(this);
      pageNum++;
    };
  })(doc.addPage);

  const totalPagesExp = '{totalPages}';

  const onEachPage = function (data) {
    addHeader(doc);
    addFooter(doc, data.pageNumber, totalPages);

    if (data.pageNumber === 1) {
      let yPos = MARGIN + 20;

      doc.setFontSize(8);
      doc.setTextColor(80, 80, 80);
      doc.text(`Generated: ${formatDateTime(now)}  |  Generated By: ${user?.name || user?.username || 'N/A'}`, MARGIN, yPos);
      yPos += 4.5;

      doc.setFontSize(8);
      doc.text(`Applied Filters: ${buildFilterSummary(filters)}`, MARGIN, yPos);
      yPos += 4.5;
      doc.text(`Total Records: ${summary.total}`, MARGIN, yPos);
      yPos += 6;

      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.3);
      doc.line(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos);
      yPos += 3;

      doc.setFontSize(9);
      doc.setTextColor(31, 78, 121);
      doc.setFont(undefined, 'bold');
      doc.text('REPORT SUMMARY', MARGIN, yPos);
      yPos += 4;
      doc.setFont(undefined, 'normal');

      const summaryItems = [
        { label: 'Total Records', value: summary.total },
        { label: 'Open Reports', value: summary.open },
        { label: 'Closed Reports', value: summary.closed },
        { label: 'Pending Reports', value: summary.pending },
        { label: 'Vendor Cases', value: summary.vendorCases },
        { label: 'Operator Cases', value: summary.operatorCases },
        { label: 'Total Cost', value: `$${summary.totalCost.toLocaleString('en-US')}` },
        { label: 'Average Cost', value: `$${summary.avgCost.toLocaleString('en-US')}` },
      ];

      const boxW = (CONTENT_WIDTH - 20) / 4;
      const boxH = 9;

      summaryItems.forEach((item, idx) => {
        const col = idx % 4;
        const row = Math.floor(idx / 4);
        const x = MARGIN + col * (boxW + 5);
        const y = yPos + row * (boxH + 2);

        doc.setFillColor(248, 250, 252);
        doc.setDrawColor(200, 200, 200);
        doc.roundedRect(x, y, boxW, boxH, 1, 1, 'FD');

        doc.setFontSize(7);
        doc.setTextColor(100, 100, 100);
        doc.text(item.label, x + 2, y + 3);

        doc.setFontSize(9);
        doc.setTextColor(31, 78, 121);
        doc.setFont(undefined, 'bold');
        doc.text(String(item.value), x + 2, y + 7.5);
        doc.setFont(undefined, 'normal');
      });

      const tableStartY = yPos + (summaryItems.length / 4) * (boxH + 2) + 4;

      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.3);
      doc.line(MARGIN, tableStartY - 1, PAGE_WIDTH - MARGIN, tableStartY - 1);

      doc.setFontSize(9);
      doc.setTextColor(31, 78, 121);
      doc.setFont(undefined, 'bold');
      doc.text('DEFECT HISTORY DETAILS', MARGIN, tableStartY + 3);
      doc.setFont(undefined, 'normal');
    } else {
      let yPos = MARGIN + 20;
      doc.setFontSize(8);
      doc.setTextColor(80, 80, 80);
      doc.text(`${COMPANY_NAME} — ${REPORT_TITLE} (continued)`, MARGIN, yPos);
      yPos += 4;
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.3);
      doc.line(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos);
    }
  };

  addWatermark(doc);

  doc.autoTable({
    startY: MARGIN + 34 + (summary.total > 0 ? 36 : 0),
    head: tableHeaders,
    body: tableData,
    theme: 'grid',
    styles: {
      fontSize: 7,
      cellPadding: 1.5,
      lineColor: [210, 210, 210],
      lineWidth: 0.2,
      textColor: [50, 50, 50],
      font: 'helvetica',
      overflow: 'ellipsize',
      minCellHeight: 5,
    },
    headStyles: {
      fillColor: [31, 78, 121],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7.5,
      halign: 'center',
      valign: 'middle',
    },
    bodyStyles: {
      valign: 'middle',
    },
    alternateRowStyles: {
      fillColor: [242, 247, 251],
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 26 },
      2: { cellWidth: 26 },
      3: { cellWidth: 22 },
      4: { cellWidth: 18 },
      5: { cellWidth: 22 },
      6: { cellWidth: 18 },
      7: { cellWidth: 18, halign: 'right' },
      8: { cellWidth: 20, halign: 'center' },
    },
    margin: { top: 30, bottom: 10, left: MARGIN, right: MARGIN },
    tableWidth: CONTENT_WIDTH,
    showHead: 'everyPage',
    tableLineColor: [210, 210, 210],
    tableLineWidth: 0.2,
    didDrawPage: function (data) {
      if (data.pageNumber > pageNum) pageNum = data.pageNumber;
    },
  });

  totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  const fileName = `Defect_History_Report_${now.getFullYear()}_${String(now.getMonth() + 1).padStart(2, '0')}_${String(now.getDate()).padStart(2, '0')}_${String(now.getHours()).padStart(2, '0')}_${String(now.getMinutes()).padStart(2, '0')}.pdf`;

  doc.save(fileName);
}
