import { MigrationInterface, QueryRunner } from "typeorm";

export class PostgresMigration1783487119085 implements MigrationInterface {
    name = 'PostgresMigration1783487119085'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_audit_log_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_log_action"`);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "emailEnabled" boolean NOT NULL DEFAULT true, "inAppEnabled" boolean NOT NULL DEFAULT true, "dailySummary" boolean NOT NULL DEFAULT false, "weeklySummary" boolean NOT NULL DEFAULT false, "immediateNotifications" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_64c90edc7310c6be7c10c96f67" UNIQUE ("user_id"), CONSTRAINT "PK_e94e2b543f2f218ee68e4f4fad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inspection_details_responsibleparty_enum" AS ENUM('OPERATOR', 'VENDOR', 'PROCESS', 'MACHINE')`);
        await queryRunner.query(`CREATE TYPE "public"."inspection_details_decision_enum" AS ENUM('REWORK', 'SCRAP', 'ALTERNATIVE')`);
        await queryRunner.query(`CREATE TABLE "inspection_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_id" uuid NOT NULL, "inspector_id" uuid NOT NULL, "errorType" character varying NOT NULL, "rootCause" text NOT NULL, "responsibleParty" "public"."inspection_details_responsibleparty_enum" NOT NULL, "responsibleId" character varying, "decision" "public"."inspection_details_decision_enum" NOT NULL, "alternativeNote" text, "costEstimate" numeric(12,2) NOT NULL DEFAULT '0', "timeEstimateHours" numeric(8,2) NOT NULL DEFAULT '0', "lossAmount" numeric(12,2), "reviewedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_76631cab38e360c3fc78518be0" UNIQUE ("report_id"), CONSTRAINT "PK_a897b2d447fa7fe552527ffed7b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sm_review" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_id" uuid NOT NULL, "sm_id" uuid NOT NULL, "loopholeNote" text NOT NULL, "decisionNote" text NOT NULL, "biasedFlag" boolean NOT NULL DEFAULT false, "forwardedToGm" boolean NOT NULL DEFAULT false, "reviewedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_a2ca31ec6e7928c90e1154f49e" UNIQUE ("report_id"), CONSTRAINT "PK_c84144e69d7081a01bb02a57958" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gm_approval" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_id" uuid NOT NULL, "gm_id" uuid NOT NULL, "approved" boolean NOT NULL, "remarks" text, "budgetApproved" numeric(12,2), "approvedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_1ee3dc9a6a2a4b827efbce8234" UNIQUE ("report_id"), CONSTRAINT "PK_00622239b97d24133df34f5a380" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "component_issue" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_id" uuid NOT NULL, "store_manager_id" uuid NOT NULL, "components" text NOT NULL, "issued_to_id" uuid NOT NULL, "remarks" text, "issuedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_157e652405efbc7bd866c30f3e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."defect_reports_raisedbyrole_enum" AS ENUM('OPERATOR', 'INSPECTOR', 'SENIOR_MANAGER')`);
        await queryRunner.query(`CREATE TYPE "public"."defect_reports_status_enum" AS ENUM('DRAFT', 'PENDING_INSPECTION', 'PENDING_SM_REVIEW', 'PENDING_GM_APPROVAL', 'APPROVED', 'REJECTED', 'COMPONENTS_ISSUED', 'REWORK_IN_PROGRESS', 'NEW_PRODUCTION', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "defect_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reportNumber" character varying, "raised_by_id" uuid NOT NULL, "raisedByRole" "public"."defect_reports_raisedbyrole_enum" NOT NULL, "scOrPoNo" character varying NOT NULL, "productId" character varying, "componentName" character varying, "errorTypeName" character varying, "partNumber" character varying, "batchNumber" character varying, "quantity" integer NOT NULL DEFAULT '1', "stageOfFailure" character varying NOT NULL, "defectDescription" text NOT NULL, "images" text NOT NULL DEFAULT '[]', "status" "public"."defect_reports_status_enum" NOT NULL DEFAULT 'DRAFT', "componentsIssued" boolean NOT NULL DEFAULT false, "componentsIssuedById" character varying, "componentsIssuedAt" TIMESTAMP, "issueRemarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ac52e87ad76c918ff4c14bd6895" UNIQUE ("reportNumber"), CONSTRAINT "PK_19a35811e4d88f0cfcb2058ec76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2164d889c45a1b3d188d5334d5" ON "defect_reports" ("raised_by_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_39b6377cf76cfa13342df6a25a" ON "defect_reports" ("scOrPoNo") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b4ae3c8725a8d7358c96a1316" ON "defect_reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_be5c084504922d0fcb83e9f0b5" ON "defect_reports" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe4a92413a52426c61a2fc8925" ON "defect_reports" ("updatedAt") `);
        await queryRunner.query(`CREATE TABLE "vendors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "contactEmail" character varying, "contactPhone" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_9c956c9797edfae5c6ddacc4e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."vendor_fault_log_recoverystatus_enum" AS ENUM('PENDING', 'RAISED', 'RECOVERED', 'PARTIALLY_RECOVERED', 'WAIVED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "vendor_fault_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_id" uuid NOT NULL, "vendor_id" uuid NOT NULL, "note" text NOT NULL, "recoveryAmount" numeric(12,2) NOT NULL DEFAULT '0', "recoveryStatus" "public"."vendor_fault_log_recoverystatus_enum" NOT NULL DEFAULT 'PENDING', "raisedAt" TIMESTAMP NOT NULL DEFAULT now(), "recoveredAt" TIMESTAMP, CONSTRAINT "PK_86d36e6d49170cd5d8982c4133f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_624041244667d71b0325319f29" ON "vendor_fault_log" ("report_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_01036d0683e89a07473b7fd230" ON "vendor_fault_log" ("vendor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_127452ba0f650fabf4399c2c98" ON "vendor_fault_log" ("recoveryStatus") `);
        await queryRunner.query(`CREATE TABLE "salary_deduction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_id" uuid NOT NULL, "operator_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "reason" text, "monthRef" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8750712923c742fce20b33a491d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('EMAIL', 'APP', 'APP_AND_EMAIL')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('QUEUED', 'SENT', 'FAILED', 'DELIVERED')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "report_id" uuid, "channel" "public"."notifications_channel_enum" NOT NULL, "type" character varying NOT NULL, "message" text NOT NULL, "read" boolean NOT NULL DEFAULT false, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'QUEUED', "attemptCount" integer NOT NULL DEFAULT '0', "sentAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "report_sequence" ("id" character varying NOT NULL, "lastValue" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_c3f3bd85d795d17be413e4ec9cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "error_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_e55020852b4fa050a3b907d8512" UNIQUE ("name"), CONSTRAINT "PK_7c9186012affd47388656f6dbdf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cost_rates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stageName" character varying NOT NULL, "ratePerHour" numeric(10,2) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f61a7d60e1a51a3fd4a69cb14c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "stockQty" integer NOT NULL DEFAULT '0', "unit" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_5409124de81d8d24ef76b4a5315" UNIQUE ("code"), CONSTRAINT "PK_0d742661c63926321b5f5eac1ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."email_logs_event_enum" AS ENUM('ReportCreated', 'ReportApproved', 'ReportRejected', 'ReportUpdated', 'Reminder', 'Escalation', 'ComponentIssued', 'VendorFault', 'SalaryDeduction', 'DailySummary', 'WeeklySummary')`);
        await queryRunner.query(`CREATE TYPE "public"."email_logs_status_enum" AS ENUM('PENDING', 'SENT', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "email_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipient" character varying NOT NULL, "cc" character varying, "bcc" character varying, "subject" character varying NOT NULL, "content" text NOT NULL, "isHtml" boolean NOT NULL DEFAULT true, "event" "public"."email_logs_event_enum" NOT NULL, "status" "public"."email_logs_status_enum" NOT NULL DEFAULT 'PENDING', "sentTime" TIMESTAMP, "retryCount" integer NOT NULL DEFAULT '0', "failureReason" text, "relatedReportId" character varying, "notificationId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_999382218924e953a790d340571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_username_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "user_email"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "passwordHash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "department" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "salaryRefId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "report_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "actor_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "actorRole" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."audit_log_actiontype_enum" AS ENUM('STATUS_CHANGE', 'FIELD_EDIT', 'INVENTORY_UPDATED', 'COMPONENT_ISSUED', 'SALARY_DEDUCTION_CREATED', 'VENDOR_FAULT_CREATED', 'IMAGE_UPLOADED')`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "actionType" "public"."audit_log_actiontype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "fieldName" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "oldValue" text`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "newValue" text`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "fromStatus" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "toStatus" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "note" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_pkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('OPERATOR', 'INSPECTOR', 'SENIOR_MANAGER', 'GENERAL_MANAGER', 'STORE_MANAGER', 'SALES', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "audit_log_pkey"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "timestamp"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_64c90edc7310c6be7c10c96f675" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inspection_details" ADD CONSTRAINT "FK_76631cab38e360c3fc78518be03" FOREIGN KEY ("report_id") REFERENCES "defect_reports"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inspection_details" ADD CONSTRAINT "FK_7ca7b4e93304913eae510d999ba" FOREIGN KEY ("inspector_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sm_review" ADD CONSTRAINT "FK_a2ca31ec6e7928c90e1154f49e4" FOREIGN KEY ("report_id") REFERENCES "defect_reports"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sm_review" ADD CONSTRAINT "FK_fb992acf7223afdaa683927ec91" FOREIGN KEY ("sm_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gm_approval" ADD CONSTRAINT "FK_1ee3dc9a6a2a4b827efbce82348" FOREIGN KEY ("report_id") REFERENCES "defect_reports"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gm_approval" ADD CONSTRAINT "FK_3545859322ca7d2fa41b0455078" FOREIGN KEY ("gm_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "component_issue" ADD CONSTRAINT "FK_27cb09a3614d4d36325fe4df530" FOREIGN KEY ("report_id") REFERENCES "defect_reports"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "component_issue" ADD CONSTRAINT "FK_d7d597c7b1c11718c355188d7fe" FOREIGN KEY ("store_manager_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "component_issue" ADD CONSTRAINT "FK_5966a927e0292b78c19ea0a141e" FOREIGN KEY ("issued_to_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "FK_b7cd653ad83e149033bff4d20a0" FOREIGN KEY ("report_id") REFERENCES "defect_reports"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "FK_15a6f5aad57db494c17986ed2e2" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "defect_reports" ADD CONSTRAINT "FK_2164d889c45a1b3d188d5334d5d" FOREIGN KEY ("raised_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vendor_fault_log" ADD CONSTRAINT "FK_624041244667d71b0325319f299" FOREIGN KEY ("report_id") REFERENCES "defect_reports"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vendor_fault_log" ADD CONSTRAINT "FK_01036d0683e89a07473b7fd230a" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_deduction" ADD CONSTRAINT "FK_5806b1b032dcea78502153922b8" FOREIGN KEY ("report_id") REFERENCES "defect_reports"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_deduction" ADD CONSTRAINT "FK_5e3eb9596a31b6f75f63a1bddf4" FOREIGN KEY ("operator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_412af9b32c6225fe444454597f9" FOREIGN KEY ("report_id") REFERENCES "defect_reports"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_412af9b32c6225fe444454597f9"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "salary_deduction" DROP CONSTRAINT "FK_5e3eb9596a31b6f75f63a1bddf4"`);
        await queryRunner.query(`ALTER TABLE "salary_deduction" DROP CONSTRAINT "FK_5806b1b032dcea78502153922b8"`);
        await queryRunner.query(`ALTER TABLE "vendor_fault_log" DROP CONSTRAINT "FK_01036d0683e89a07473b7fd230a"`);
        await queryRunner.query(`ALTER TABLE "vendor_fault_log" DROP CONSTRAINT "FK_624041244667d71b0325319f299"`);
        await queryRunner.query(`ALTER TABLE "defect_reports" DROP CONSTRAINT "FK_2164d889c45a1b3d188d5334d5d"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "FK_15a6f5aad57db494c17986ed2e2"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "FK_b7cd653ad83e149033bff4d20a0"`);
        await queryRunner.query(`ALTER TABLE "component_issue" DROP CONSTRAINT "FK_5966a927e0292b78c19ea0a141e"`);
        await queryRunner.query(`ALTER TABLE "component_issue" DROP CONSTRAINT "FK_d7d597c7b1c11718c355188d7fe"`);
        await queryRunner.query(`ALTER TABLE "component_issue" DROP CONSTRAINT "FK_27cb09a3614d4d36325fe4df530"`);
        await queryRunner.query(`ALTER TABLE "gm_approval" DROP CONSTRAINT "FK_3545859322ca7d2fa41b0455078"`);
        await queryRunner.query(`ALTER TABLE "gm_approval" DROP CONSTRAINT "FK_1ee3dc9a6a2a4b827efbce82348"`);
        await queryRunner.query(`ALTER TABLE "sm_review" DROP CONSTRAINT "FK_fb992acf7223afdaa683927ec91"`);
        await queryRunner.query(`ALTER TABLE "sm_review" DROP CONSTRAINT "FK_a2ca31ec6e7928c90e1154f49e4"`);
        await queryRunner.query(`ALTER TABLE "inspection_details" DROP CONSTRAINT "FK_7ca7b4e93304913eae510d999ba"`);
        await queryRunner.query(`ALTER TABLE "inspection_details" DROP CONSTRAINT "FK_76631cab38e360c3fc78518be03"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_64c90edc7310c6be7c10c96f675"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "timestamp"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(10) NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "toStatus"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "fromStatus"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "newValue"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "oldValue"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "fieldName"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "actionType"`);
        await queryRunner.query(`DROP TYPE "public"."audit_log_actiontype_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "actorRole"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "actor_id"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP COLUMN "report_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "salaryRefId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "department"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "passwordHash"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "ip_address" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "entity_id" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "entity_type" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "action" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "user_email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying(15) NOT NULL DEFAULT 'approved'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_username_key" UNIQUE ("username")`);
        await queryRunner.query(`DROP TABLE "email_logs"`);
        await queryRunner.query(`DROP TYPE "public"."email_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."email_logs_event_enum"`);
        await queryRunner.query(`DROP TABLE "components"`);
        await queryRunner.query(`DROP TABLE "cost_rates"`);
        await queryRunner.query(`DROP TABLE "error_types"`);
        await queryRunner.query(`DROP TABLE "report_sequence"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TABLE "salary_deduction"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_127452ba0f650fabf4399c2c98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01036d0683e89a07473b7fd230"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_624041244667d71b0325319f29"`);
        await queryRunner.query(`DROP TABLE "vendor_fault_log"`);
        await queryRunner.query(`DROP TYPE "public"."vendor_fault_log_recoverystatus_enum"`);
        await queryRunner.query(`DROP TABLE "vendors"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe4a92413a52426c61a2fc8925"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be5c084504922d0fcb83e9f0b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b4ae3c8725a8d7358c96a1316"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39b6377cf76cfa13342df6a25a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2164d889c45a1b3d188d5334d5"`);
        await queryRunner.query(`DROP TABLE "defect_reports"`);
        await queryRunner.query(`DROP TYPE "public"."defect_reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."defect_reports_raisedbyrole_enum"`);
        await queryRunner.query(`DROP TABLE "component_issue"`);
        await queryRunner.query(`DROP TABLE "gm_approval"`);
        await queryRunner.query(`DROP TABLE "sm_review"`);
        await queryRunner.query(`DROP TABLE "inspection_details"`);
        await queryRunner.query(`DROP TYPE "public"."inspection_details_decision_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inspection_details_responsibleparty_enum"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`CREATE INDEX "idx_audit_log_action" ON "audit_log" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_log_timestamp" ON "audit_log" ("timestamp") `);
    }

}
